# Generated by Django 3.1.14 on 2023-03-21 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название покемона на русском')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название покемона на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название покемона на японском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение покемона')),
                ('description', models.TextField(default='Описание в разработке', verbose_name='Описание покемона')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Предыдущая эволюция покемона')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата, время появления')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата, время исчезновения')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень покемона')),
                ('health', models.IntegerField(default=0, verbose_name='Здоровье покемона')),
                ('strength', models.IntegerField(default=0, verbose_name='Сила покемона')),
                ('defense', models.IntegerField(default=0, verbose_name='Защита покемона')),
                ('stamina', models.IntegerField(default=0, verbose_name='Выносливость покемона')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
