# Generated by Django 3.1.14 on 2023-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20230319_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='log',
            new_name='lon',
        ),
    ]
